version: '3.8'

services:
  # Nginx Load Balancer
  nginx-lb:
    image: nginx:alpine
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app-network

  # Server 1
  server1:
    image: nginx:alpine
    container_name: server1
    volumes:
      - ./page/server1.html:/usr/share/nginx/html/index.html
    networks:
      - app-network
    expose:
      - "80"

  # Server 2
  server2:
    image: nginx:alpine
    container_name: server2
    volumes:
      - ./page/server2.html:/usr/share/nginx/html/index.html
    networks:
      - app-network
    expose:
      - "80"

  # Server 3
  server3:
    image: nginx:alpine
    container_name: server3
    volumes:
      - ./page/server3.html:/usr/share/nginx/html/index.html
    networks:
      - app-network
    expose:
      - "80"

networks:
  app-network:
    driver: bridge